[component]
structures = [ "content_blocks" ]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
form_title = "Contáctanos"
form_description = "Quisieramos saber más de ti"
form_success_page = "/"
form_submission_email = "site@example.com" # Add your email for contact form
form_button_text = "Send now"
